name: .NET Core

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: |
           cd HitomiApi
           dotnet restore
    - name: Build
      run: |
           cd HitomiApi
           dotnet build --configuration Release --no-restore
    - name: Publish
      run: |
           cd HitomiApi
           dotnet publish -c Release --self-contained -r ubuntu.18.04-x64
    - name: Test
      run: |
           cd HitomiApi
           dotnet test --no-restore --verbosity normal
